### ISSUE TITLE
timezone issue

### ISSUE THREAD

**Issue by tdavis6** [tdavis6/dailySummaryEmail#126]
INFO:root:Timezone validated as: America/Chicago
INFO:apscheduler.scheduler:Removed job daily_email_job
INFO:apscheduler.scheduler:Added job "scheduled_email_job" to job store "default"
INFO:root:Daily email job rescheduled at 6:00 for the next day.
INFO:root:Configuration refreshed.
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:root:Email sent successfully on 2024-12-10 20:14:44 -0600.
INFO:root:Email sent successfully.
INFO:root:Timezone validated as: America/Chicago
INFO:root:Configuration refreshed.
CRITICAL:root:An error occurred: could not convert string to float: ''
CRITICAL:root:Error validating TIMEZONE: TIMEZONE could not be determined. Coordinates or Address may be missing.
ERROR:root:Invalid LATITUDE and LONGITUDE. Attempting to resolve from ADDRESS.
INFO:root:Location data saved to cache.
INFO:root:Location data saved to cache.
INFO:root:Configuration refreshed.
CRITICAL:root:Failed to get events: 'NoneType' object has no attribute 'localize'
CRITICAL:root:Failed to get events: 'NoneType' object has no attribute 'localize'
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:root:Email sent successfully on 2024-12-11 02:15:42 .
INFO:root:Email sent successfully.
CRITICAL:root:Error sending email: 'NoneType' object has no attribute 'localize'
CRITICAL:root:Traceback: Traceback (most recent call last):
  File "/app/src/main.py", line 324, in prepare_send_email
    todo_string = get_todo() or ""
                  ^^^^^^^^^^
  File "/app/src/main.py", line 271, in get_todo
    todo = get_todo_tasks(
           ^^^^^^^^^^^^^^^
  File "/app/src/get_todo_tasks.py", line 30, in get_todo_tasks
    tasks_text += process_tasks(
                  ^^^^^^^^^^^^^^
  File "/app/src/get_todo_tasks.py", line 73, in process_tasks
    due_dt = timezone.localize(due_dt)
             ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'localize'
CRITICAL:root:Error sending email: 'NoneType' object has no attribute 'localize'
CRITICAL:root:Traceback: Traceback (most recent call last):
  File "/app/src/main.py", line 324, in prepare_send_email
    todo_string = get_todo() or ""
                  ^^^^^^^^^^
  File "/app/src/main.py", line 271, in get_todo
    todo = get_todo_tasks(
           ^^^^^^^^^^^^^^^
  File "/app/src/get_todo_tasks.py", line 30, in get_todo_tasks
    tasks_text += process_tasks(
                  ^^^^^^^^^^^^^^
  File "/app/src/get_todo_tasks.py", line 73, in process_tasks
    due_dt = timezone.localize(due_dt)
             ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'localize'

**Comment by tdavis6** [comment]
Only occurs when, after the container has started, the coordinates are removed
